// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const accessCandidates = `-- name: AccessCandidates :many
SELECT student_id FROM trial_feedback WHERE liked
UNION
SELECT student_id FROM channel_access WHERE active
`

func (q *Queries) AccessCandidates(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, accessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var student_id int64
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessFacts = `-- name: AccessFacts :one

SELECT
    EXISTS (SELECT 1 FROM trial_feedback f WHERE f.student_id = $1 AND f.liked) AS liked,
    EXISTS (SELECT 1 FROM channel_access c WHERE c.student_id = $1 AND c.active) AS active,
    COALESCE((SELECT c.granted_at FROM channel_access c WHERE c.student_id = $1 AND c.active), 'epoch'::timestamptz)::timestamptz AS granted_at,
    COALESCE((SELECT max(l.starts_at) FROM lessons l WHERE l.student_id = $1 AND l.status = 'held'), 'epoch'::timestamptz)::timestamptz AS last_held,
    EXISTS (SELECT 1 FROM lessons l WHERE l.student_id = $1 AND l.status = 'scheduled' AND l.starts_at > $2) AS has_upcoming
`

type AccessFactsParams struct {
	StudentID int64
	Now       time.Time
}

type AccessFactsRow struct {
	Liked       bool
	Active      bool
	GrantedAt   time.Time
	LastHeld    time.Time
	HasUpcoming bool
}

// ---- доступ в закрытый канал ----
func (q *Queries) AccessFacts(ctx context.Context, arg AccessFactsParams) (AccessFactsRow, error) {
	row := q.db.QueryRowContext(ctx, accessFacts, arg.StudentID, arg.Now)
	var i AccessFactsRow
	err := row.Scan(
		&i.Liked,
		&i.Active,
		&i.GrantedAt,
		&i.LastHeld,
		&i.HasUpcoming,
	)
	return i, err
}

const balance = `-- name: Balance :one
SELECT COALESCE(SUM(delta), 0)::int AS balance FROM ledger WHERE student_id = $1 AND tutor_id = $2
`

type BalanceParams struct {
	StudentID int64
	TutorID   int64
}

func (q *Queries) Balance(ctx context.Context, arg BalanceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, balance, arg.StudentID, arg.TutorID)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}

const feedbackByID = `-- name: FeedbackByID :one
SELECT id, lesson_id, student_id, tutor_id, liked, comment, forwarded_at, created_at, student_name, tutor_name FROM feedback_details WHERE id = $1
`

func (q *Queries) FeedbackByID(ctx context.Context, id int64) (FeedbackDetail, error) {
	row := q.db.QueryRowContext(ctx, feedbackByID, id)
	var i FeedbackDetail
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.StudentID,
		&i.TutorID,
		&i.Liked,
		&i.Comment,
		&i.ForwardedAt,
		&i.CreatedAt,
		&i.StudentName,
		&i.TutorName,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM app_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const grantAccess = `-- name: GrantAccess :execrows
INSERT INTO channel_access (student_id) VALUES ($1)
ON CONFLICT (student_id) DO UPDATE SET active = true, granted_at = now(), revoked_at = NULL
WHERE NOT channel_access.active
`

func (q *Queries) GrantAccess(ctx context.Context, studentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, grantAccess, studentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertFeedback = `-- name: InsertFeedback :one

INSERT INTO trial_feedback (lesson_id, student_id, tutor_id, liked) VALUES ($1, $2, $3, $4)
ON CONFLICT (lesson_id) DO NOTHING RETURNING id
`

type InsertFeedbackParams struct {
	LessonID  int64
	StudentID int64
	TutorID   int64
	Liked     bool
}

// ---- отзывы о пробных ----
func (q *Queries) InsertFeedback(ctx context.Context, arg InsertFeedbackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFeedback,
		arg.LessonID,
		arg.StudentID,
		arg.TutorID,
		arg.Liked,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLedger = `-- name: InsertLedger :exec
INSERT INTO ledger (student_id, tutor_id, delta, unit_price, reason, payment_id, lesson_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT DO NOTHING
`

type InsertLedgerParams struct {
	StudentID int64
	TutorID   int64
	Delta     int32
	UnitPrice int64
	Reason    string
	PaymentID sql.NullInt64
	LessonID  sql.NullInt64
	ExpiresAt sql.NullTime
}

// Списание за урок идемпотентно: уникальный индекс по lesson_id для reason = 'lesson'.
func (q *Queries) InsertLedger(ctx context.Context, arg InsertLedgerParams) error {
	_, err := q.db.ExecContext(ctx, insertLedger,
		arg.StudentID,
		arg.TutorID,
		arg.Delta,
		arg.UnitPrice,
		arg.Reason,
		arg.PaymentID,
		arg.LessonID,
		arg.ExpiresAt,
	)
	return err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (payer_id, student_id, tutor_id, product_id, amount)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type InsertPaymentParams struct {
	PayerID   int64
	StudentID int64
	TutorID   int64
	ProductID int32
	Amount    int64
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPayment,
		arg.PayerID,
		arg.StudentID,
		arg.TutorID,
		arg.ProductID,
		arg.Amount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProduct = `-- name: InsertProduct :exec
INSERT INTO products (name, kind, lessons, discount_pct, valid_days)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProductParams struct {
	Name        string
	Kind        string
	Lessons     int32
	DiscountPct int32
	ValidDays   sql.NullInt32
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.ExecContext(ctx, insertProduct,
		arg.Name,
		arg.Kind,
		arg.Lessons,
		arg.DiscountPct,
		arg.ValidDays,
	)
	return err
}

const likedTutor = `-- name: LikedTutor :one
SELECT EXISTS (SELECT 1 FROM trial_feedback WHERE student_id = $1 AND tutor_id = $2 AND liked)
`

type LikedTutorParams struct {
	StudentID int64
	TutorID   int64
}

func (q *Queries) LikedTutor(ctx context.Context, arg LikedTutorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, likedTutor, arg.StudentID, arg.TutorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, kind, lessons, discount_pct, valid_days, active FROM products WHERE active OR NOT $1::boolean ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context, onlyActive bool) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, onlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Lessons,
			&i.DiscountPct,
			&i.ValidDays,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markForwarded = `-- name: MarkForwarded :execrows
UPDATE trial_feedback SET forwarded_at = now() WHERE id = $1 AND forwarded_at IS NULL
`

func (q *Queries) MarkForwarded(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markForwarded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const productByID = `-- name: ProductByID :one
SELECT id, name, kind, lessons, discount_pct, valid_days, active FROM products WHERE id = $1
`

func (q *Queries) ProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, productByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Lessons,
		&i.DiscountPct,
		&i.ValidDays,
		&i.Active,
	)
	return i, err
}

const recentFeedback = `-- name: RecentFeedback :many
SELECT id, lesson_id, student_id, tutor_id, liked, comment, forwarded_at, created_at, student_name, tutor_name FROM feedback_details ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) RecentFeedback(ctx context.Context, limit int32) ([]FeedbackDetail, error) {
	rows, err := q.db.QueryContext(ctx, recentFeedback, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedbackDetail{}
	for rows.Next() {
		var i FeedbackDetail
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.StudentID,
			&i.TutorID,
			&i.Liked,
			&i.Comment,
			&i.ForwardedAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.TutorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccess = `-- name: RevokeAccess :execrows
UPDATE channel_access SET active = false, revoked_at = now() WHERE student_id = $1 AND active
`

func (q *Queries) RevokeAccess(ctx context.Context, studentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAccess, studentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setFeedbackComment = `-- name: SetFeedbackComment :exec
UPDATE trial_feedback SET comment = $1 WHERE id = $2
`

type SetFeedbackCommentParams struct {
	Comment string
	ID      int64
}

func (q *Queries) SetFeedbackComment(ctx context.Context, arg SetFeedbackCommentParams) error {
	_, err := q.db.ExecContext(ctx, setFeedbackComment, arg.Comment, arg.ID)
	return err
}

const toggleProduct = `-- name: ToggleProduct :exec
UPDATE products SET active = NOT active WHERE id = $1
`

func (q *Queries) ToggleProduct(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, toggleProduct, id)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO app_settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
