// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const activeRecurring = `-- name: ActiveRecurring :many
SELECT id, student_id, tutor_id, subject_id, weekday, start_min, duration_min, active, created_at FROM recurring_slots WHERE active ORDER BY id
`

func (q *Queries) ActiveRecurring(ctx context.Context) ([]RecurringSlot, error) {
	rows, err := q.db.QueryContext(ctx, activeRecurring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringSlot{}
	for rows.Next() {
		var i RecurringSlot
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.SubjectID,
			&i.Weekday,
			&i.StartMin,
			&i.DurationMin,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const busyIntervals = `-- name: BusyIntervals :many
SELECT starts_at, ends_at FROM lesson_details
WHERE status = 'scheduled' AND (tutor_id = $1 OR student_id = $2) AND id <> $3
  AND starts_at < $4 AND ends_at > $5
`

type BusyIntervalsParams struct {
	TutorID   int64
	StudentID int64
	ExcludeID int64
	ToTime    time.Time
	FromTime  time.Time
}

type BusyIntervalsRow struct {
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) BusyIntervals(ctx context.Context, arg BusyIntervalsParams) ([]BusyIntervalsRow, error) {
	rows, err := q.db.QueryContext(ctx, busyIntervals,
		arg.TutorID,
		arg.StudentID,
		arg.ExcludeID,
		arg.ToTime,
		arg.FromTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusyIntervalsRow{}
	for rows.Next() {
		var i BusyIntervalsRow
		if err := rows.Scan(&i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelFutureRecurringLessons = `-- name: CancelFutureRecurringLessons :execrows
UPDATE lessons SET status = 'cancelled', cancelled_by = $1, cancel_reason = $2
WHERE recurring_slot_id = $3 AND status = 'scheduled' AND starts_at > now()
`

type CancelFutureRecurringLessonsParams struct {
	CancelledBy  sql.NullInt64
	CancelReason string
	SlotID       sql.NullInt64
}

func (q *Queries) CancelFutureRecurringLessons(ctx context.Context, arg CancelFutureRecurringLessonsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelFutureRecurringLessons, arg.CancelledBy, arg.CancelReason, arg.SlotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelLesson = `-- name: CancelLesson :execrows
UPDATE lessons SET status = 'cancelled', cancelled_by = $1, cancel_reason = $2, late_cancel = $3
WHERE id = $4 AND status = 'scheduled'
`

type CancelLessonParams struct {
	CancelledBy  sql.NullInt64
	CancelReason string
	LateCancel   bool
	ID           int64
}

func (q *Queries) CancelLesson(ctx context.Context, arg CancelLessonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelLesson,
		arg.CancelledBy,
		arg.CancelReason,
		arg.LateCancel,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const changeRequestByID = `-- name: ChangeRequestByID :one
SELECT id, lesson_id, requested_by, kind, new_starts_at, reason, status, decided_by, created_at FROM change_requests WHERE id = $1
`

func (q *Queries) ChangeRequestByID(ctx context.Context, id int64) (ChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, changeRequestByID, id)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.RequestedBy,
		&i.Kind,
		&i.NewStartsAt,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.CreatedAt,
	)
	return i, err
}

const claimPrompt = `-- name: ClaimPrompt :execrows
UPDATE lessons SET mark_prompted = true WHERE id = $1 AND NOT mark_prompted AND status = 'scheduled'
`

func (q *Queries) ClaimPrompt(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimPrompt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deactivateRecurring = `-- name: DeactivateRecurring :exec
UPDATE recurring_slots SET active = false WHERE id = $1
`

func (q *Queries) DeactivateRecurring(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateRecurring, id)
	return err
}

const debugShiftLesson = `-- name: DebugShiftLesson :exec
UPDATE lessons SET starts_at = $1, mark_prompted = false WHERE id = $2 AND status = 'scheduled'
`

type DebugShiftLessonParams struct {
	StartsAt time.Time
	ID       int64
}

func (q *Queries) DebugShiftLesson(ctx context.Context, arg DebugShiftLessonParams) error {
	_, err := q.db.ExecContext(ctx, debugShiftLesson, arg.StartsAt, arg.ID)
	return err
}

const decideChangeRequest = `-- name: DecideChangeRequest :execrows
UPDATE change_requests SET status = $1, decided_by = $2 WHERE id = $3 AND status = 'pending'
`

type DecideChangeRequestParams struct {
	Status    string
	DecidedBy sql.NullInt64
	ID        int64
}

func (q *Queries) DecideChangeRequest(ctx context.Context, arg DecideChangeRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideChangeRequest, arg.Status, arg.DecidedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const hasTrial = `-- name: HasTrial :one
SELECT EXISTS (SELECT 1 FROM lessons
    WHERE student_id = $1 AND tutor_id = $2 AND kind = 'trial' AND status <> 'cancelled')
`

type HasTrialParams struct {
	StudentID int64
	TutorID   int64
}

func (q *Queries) HasTrial(ctx context.Context, arg HasTrialParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasTrial, arg.StudentID, arg.TutorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertChangeRequest = `-- name: InsertChangeRequest :one

INSERT INTO change_requests (lesson_id, requested_by, kind, new_starts_at, reason)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type InsertChangeRequestParams struct {
	LessonID    int64
	RequestedBy int64
	Kind        string
	NewStartsAt sql.NullTime
	Reason      string
}

// ---- запросы на перенос/отмену ----
func (q *Queries) InsertChangeRequest(ctx context.Context, arg InsertChangeRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangeRequest,
		arg.LessonID,
		arg.RequestedBy,
		arg.Kind,
		arg.NewStartsAt,
		arg.Reason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLesson = `-- name: InsertLesson :one
INSERT INTO lessons (student_id, tutor_id, subject_id, starts_at, duration_min, kind, recurring_slot_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertLessonParams struct {
	StudentID       int64
	TutorID         int64
	SubjectID       int32
	StartsAt        time.Time
	DurationMin     int32
	Kind            string
	RecurringSlotID sql.NullInt64
}

func (q *Queries) InsertLesson(ctx context.Context, arg InsertLessonParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLesson,
		arg.StudentID,
		arg.TutorID,
		arg.SubjectID,
		arg.StartsAt,
		arg.DurationMin,
		arg.Kind,
		arg.RecurringSlotID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRecurring = `-- name: InsertRecurring :one

INSERT INTO recurring_slots (student_id, tutor_id, subject_id, weekday, start_min, duration_min)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type InsertRecurringParams struct {
	StudentID   int64
	TutorID     int64
	SubjectID   int32
	Weekday     int16
	StartMin    int32
	DurationMin int32
}

// ---- постоянные слоты ----
func (q *Queries) InsertRecurring(ctx context.Context, arg InsertRecurringParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRecurring,
		arg.StudentID,
		arg.TutorID,
		arg.SubjectID,
		arg.Weekday,
		arg.StartMin,
		arg.DurationMin,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRecurringLesson = `-- name: InsertRecurringLesson :execrows
INSERT INTO lessons (student_id, tutor_id, subject_id, starts_at, duration_min, kind, recurring_slot_id)
VALUES ($1, $2, $3, $4, $5, 'regular', $6)
ON CONFLICT DO NOTHING
`

type InsertRecurringLessonParams struct {
	StudentID       int64
	TutorID         int64
	SubjectID       int32
	StartsAt        time.Time
	DurationMin     int32
	RecurringSlotID sql.NullInt64
}

func (q *Queries) InsertRecurringLesson(ctx context.Context, arg InsertRecurringLessonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertRecurringLesson,
		arg.StudentID,
		arg.TutorID,
		arg.SubjectID,
		arg.StartsAt,
		arg.DurationMin,
		arg.RecurringSlotID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lateCancels = `-- name: LateCancels :many
SELECT id, student_id, tutor_id, subject_id, starts_at, duration_min, kind, status, recurring_slot_id, cancelled_by, cancel_reason, late_cancel, mark_prompted, marked_auto, created_at, subject, student_name, tutor_name, ends_at FROM lesson_details WHERE late_cancel ORDER BY starts_at DESC LIMIT $1
`

func (q *Queries) LateCancels(ctx context.Context, limit int32) ([]LessonDetail, error) {
	rows, err := q.db.QueryContext(ctx, lateCancels, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonDetail{}
	for rows.Next() {
		var i LessonDetail
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.SubjectID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Kind,
			&i.Status,
			&i.RecurringSlotID,
			&i.CancelledBy,
			&i.CancelReason,
			&i.LateCancel,
			&i.MarkPrompted,
			&i.MarkedAuto,
			&i.CreatedAt,
			&i.Subject,
			&i.StudentName,
			&i.TutorName,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lessonByID = `-- name: LessonByID :one
SELECT id, student_id, tutor_id, subject_id, starts_at, duration_min, kind, status, recurring_slot_id, cancelled_by, cancel_reason, late_cancel, mark_prompted, marked_auto, created_at, subject, student_name, tutor_name, ends_at FROM lesson_details WHERE id = $1
`

func (q *Queries) LessonByID(ctx context.Context, id int64) (LessonDetail, error) {
	row := q.db.QueryRowContext(ctx, lessonByID, id)
	var i LessonDetail
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TutorID,
		&i.SubjectID,
		&i.StartsAt,
		&i.DurationMin,
		&i.Kind,
		&i.Status,
		&i.RecurringSlotID,
		&i.CancelledBy,
		&i.CancelReason,
		&i.LateCancel,
		&i.MarkPrompted,
		&i.MarkedAuto,
		&i.CreatedAt,
		&i.Subject,
		&i.StudentName,
		&i.TutorName,
		&i.EndsAt,
	)
	return i, err
}

const lessonsEndedBefore = `-- name: LessonsEndedBefore :many
SELECT id, student_id, tutor_id, subject_id, starts_at, duration_min, kind, status, recurring_slot_id, cancelled_by, cancel_reason, late_cancel, mark_prompted, marked_auto, created_at, subject, student_name, tutor_name, ends_at FROM lesson_details
WHERE status = 'scheduled' AND ends_at <= $1
ORDER BY starts_at LIMIT 100
`

func (q *Queries) LessonsEndedBefore(ctx context.Context, before time.Time) ([]LessonDetail, error) {
	rows, err := q.db.QueryContext(ctx, lessonsEndedBefore, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonDetail{}
	for rows.Next() {
		var i LessonDetail
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.SubjectID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Kind,
			&i.Status,
			&i.RecurringSlotID,
			&i.CancelledBy,
			&i.CancelReason,
			&i.LateCancel,
			&i.MarkPrompted,
			&i.MarkedAuto,
			&i.CreatedAt,
			&i.Subject,
			&i.StudentName,
			&i.TutorName,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lessonsStartingBetween = `-- name: LessonsStartingBetween :many
SELECT id, student_id, tutor_id, subject_id, starts_at, duration_min, kind, status, recurring_slot_id, cancelled_by, cancel_reason, late_cancel, mark_prompted, marked_auto, created_at, subject, student_name, tutor_name, ends_at FROM lesson_details
WHERE status = 'scheduled' AND starts_at >= $1 AND starts_at < $2
ORDER BY starts_at
`

type LessonsStartingBetweenParams struct {
	FromTime time.Time
	ToTime   time.Time
}

func (q *Queries) LessonsStartingBetween(ctx context.Context, arg LessonsStartingBetweenParams) ([]LessonDetail, error) {
	rows, err := q.db.QueryContext(ctx, lessonsStartingBetween, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonDetail{}
	for rows.Next() {
		var i LessonDetail
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.SubjectID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Kind,
			&i.Status,
			&i.RecurringSlotID,
			&i.CancelledBy,
			&i.CancelReason,
			&i.LateCancel,
			&i.MarkPrompted,
			&i.MarkedAuto,
			&i.CreatedAt,
			&i.Subject,
			&i.StudentName,
			&i.TutorName,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lessonsToPrompt = `-- name: LessonsToPrompt :many
SELECT id, student_id, tutor_id, subject_id, starts_at, duration_min, kind, status, recurring_slot_id, cancelled_by, cancel_reason, late_cancel, mark_prompted, marked_auto, created_at, subject, student_name, tutor_name, ends_at FROM lesson_details
WHERE status = 'scheduled' AND NOT mark_prompted AND ends_at <= $1
ORDER BY starts_at LIMIT 100
`

func (q *Queries) LessonsToPrompt(ctx context.Context, now time.Time) ([]LessonDetail, error) {
	rows, err := q.db.QueryContext(ctx, lessonsToPrompt, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonDetail{}
	for rows.Next() {
		var i LessonDetail
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.SubjectID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Kind,
			&i.Status,
			&i.RecurringSlotID,
			&i.CancelledBy,
			&i.CancelReason,
			&i.LateCancel,
			&i.MarkPrompted,
			&i.MarkedAuto,
			&i.CreatedAt,
			&i.Subject,
			&i.StudentName,
			&i.TutorName,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTutor = `-- name: LockTutor :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Транзакционная блокировка расписания репетитора: две параллельные записи не займут одно окно.
func (q *Queries) LockTutor(ctx context.Context, tutorID int64) error {
	_, err := q.db.ExecContext(ctx, lockTutor, tutorID)
	return err
}

const logReminder = `-- name: LogReminder :execrows
INSERT INTO reminder_log (lesson_id, user_id, kind) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type LogReminderParams struct {
	LessonID int64
	UserID   int64
	Kind     string
}

func (q *Queries) LogReminder(ctx context.Context, arg LogReminderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, logReminder, arg.LessonID, arg.UserID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const moveLesson = `-- name: MoveLesson :exec
UPDATE lessons SET starts_at = $1, late_cancel = late_cancel OR $2::boolean,
    cancel_reason = CASE WHEN $3::text <> '' THEN $3::text ELSE cancel_reason END,
    recurring_slot_id = NULL, mark_prompted = false
WHERE id = $4 AND status = 'scheduled'
`

type MoveLessonParams struct {
	StartsAt time.Time
	Late     bool
	Reason   string
	ID       int64
}

func (q *Queries) MoveLesson(ctx context.Context, arg MoveLessonParams) error {
	_, err := q.db.ExecContext(ctx, moveLesson,
		arg.StartsAt,
		arg.Late,
		arg.Reason,
		arg.ID,
	)
	return err
}

const recurringByID = `-- name: RecurringByID :one
SELECT id, student_id, tutor_id, subject_id, weekday, start_min, duration_min, active, created_at FROM recurring_slots WHERE id = $1
`

func (q *Queries) RecurringByID(ctx context.Context, id int64) (RecurringSlot, error) {
	row := q.db.QueryRowContext(ctx, recurringByID, id)
	var i RecurringSlot
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TutorID,
		&i.SubjectID,
		&i.Weekday,
		&i.StartMin,
		&i.DurationMin,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const setLessonStatus = `-- name: SetLessonStatus :execrows
UPDATE lessons SET status = $1, marked_auto = $2 WHERE id = $3 AND status = 'scheduled'
`

type SetLessonStatusParams struct {
	Status     string
	MarkedAuto bool
	ID         int64
}

func (q *Queries) SetLessonStatus(ctx context.Context, arg SetLessonStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setLessonStatus, arg.Status, arg.MarkedAuto, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upcomingForStudent = `-- name: UpcomingForStudent :many
SELECT id, student_id, tutor_id, subject_id, starts_at, duration_min, kind, status, recurring_slot_id, cancelled_by, cancel_reason, late_cancel, mark_prompted, marked_auto, created_at, subject, student_name, tutor_name, ends_at FROM lesson_details
WHERE student_id = $1 AND status = 'scheduled' AND ends_at > now()
ORDER BY starts_at LIMIT $2
`

type UpcomingForStudentParams struct {
	StudentID int64
	MaxRows   int32
}

func (q *Queries) UpcomingForStudent(ctx context.Context, arg UpcomingForStudentParams) ([]LessonDetail, error) {
	rows, err := q.db.QueryContext(ctx, upcomingForStudent, arg.StudentID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonDetail{}
	for rows.Next() {
		var i LessonDetail
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.SubjectID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Kind,
			&i.Status,
			&i.RecurringSlotID,
			&i.CancelledBy,
			&i.CancelReason,
			&i.LateCancel,
			&i.MarkPrompted,
			&i.MarkedAuto,
			&i.CreatedAt,
			&i.Subject,
			&i.StudentName,
			&i.TutorName,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upcomingForTutor = `-- name: UpcomingForTutor :many
SELECT id, student_id, tutor_id, subject_id, starts_at, duration_min, kind, status, recurring_slot_id, cancelled_by, cancel_reason, late_cancel, mark_prompted, marked_auto, created_at, subject, student_name, tutor_name, ends_at FROM lesson_details
WHERE tutor_id = $1 AND status = 'scheduled' AND ends_at > now()
ORDER BY starts_at LIMIT $2
`

type UpcomingForTutorParams struct {
	TutorID int64
	MaxRows int32
}

func (q *Queries) UpcomingForTutor(ctx context.Context, arg UpcomingForTutorParams) ([]LessonDetail, error) {
	rows, err := q.db.QueryContext(ctx, upcomingForTutor, arg.TutorID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonDetail{}
	for rows.Next() {
		var i LessonDetail
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.SubjectID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Kind,
			&i.Status,
			&i.RecurringSlotID,
			&i.CancelledBy,
			&i.CancelReason,
			&i.LateCancel,
			&i.MarkPrompted,
			&i.MarkedAuto,
			&i.CreatedAt,
			&i.Subject,
			&i.StudentName,
			&i.TutorName,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
