// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AppSetting struct {
	Key   string
	Value string
}

type ChangeRequest struct {
	ID          int64
	LessonID    int64
	RequestedBy int64
	Kind        string
	NewStartsAt sql.NullTime
	Reason      string
	Status      string
	DecidedBy   sql.NullInt64
	CreatedAt   time.Time
}

type ChannelAccess struct {
	StudentID int64
	Active    bool
	GrantedAt time.Time
	RevokedAt sql.NullTime
}

type Enrollment struct {
	ID        int64
	StudentID int64
	TutorID   int64
	SubjectID int32
	Active    bool
	StartedAt time.Time
	EndedAt   sql.NullTime
}

type FeedbackDetail struct {
	ID          int64
	LessonID    int64
	StudentID   int64
	TutorID     int64
	Liked       bool
	Comment     string
	ForwardedAt sql.NullTime
	CreatedAt   time.Time
	StudentName string
	TutorName   string
}

type Identity struct {
	Provider   string
	ExternalID string
	UserID     int64
	ChatID     string
	Username   string
	LastSeenAt time.Time
}

type Invite struct {
	Code      string
	Kind      string
	CreatedBy int64
	TargetID  sql.NullInt64
	ExpiresAt time.Time
	UsedAt    sql.NullTime
}

type Ledger struct {
	ID        int64
	StudentID int64
	TutorID   int64
	Delta     int32
	UnitPrice int64
	Reason    string
	PaymentID sql.NullInt64
	LessonID  sql.NullInt64
	ExpiresAt sql.NullTime
	CreatedAt time.Time
}

type Lesson struct {
	ID              int64
	StudentID       int64
	TutorID         int64
	SubjectID       int32
	StartsAt        time.Time
	DurationMin     int32
	Kind            string
	Status          string
	RecurringSlotID sql.NullInt64
	CancelledBy     sql.NullInt64
	CancelReason    string
	LateCancel      bool
	MarkPrompted    bool
	MarkedAuto      bool
	CreatedAt       time.Time
}

type LessonDetail struct {
	ID              int64
	StudentID       int64
	TutorID         int64
	SubjectID       int32
	StartsAt        time.Time
	DurationMin     int32
	Kind            string
	Status          string
	RecurringSlotID sql.NullInt64
	CancelledBy     sql.NullInt64
	CancelReason    string
	LateCancel      bool
	MarkPrompted    bool
	MarkedAuto      bool
	CreatedAt       time.Time
	Subject         string
	StudentName     string
	TutorName       string
	EndsAt          time.Time
}

type Outbox struct {
	ID            int64
	Provider      string
	Kind          string
	ChatID        string
	ExternalID    string
	Payload       json.RawMessage
	Status        string
	Attempts      int32
	LastError     string
	NextAttemptAt time.Time
	CreatedAt     time.Time
	SentAt        sql.NullTime
}

type ParentLink struct {
	ParentID  int64
	StudentID int64
}

type Payment struct {
	ID        int64
	PayerID   int64
	StudentID int64
	TutorID   int64
	ProductID int32
	Amount    int64
	Status    string
	CreatedAt time.Time
}

type Product struct {
	ID          int32
	Name        string
	Kind        string
	Lessons     int32
	DiscountPct int32
	ValidDays   sql.NullInt32
	Active      bool
}

type RecurringSlot struct {
	ID          int64
	StudentID   int64
	TutorID     int64
	SubjectID   int32
	Weekday     int16
	StartMin    int32
	DurationMin int32
	Active      bool
	CreatedAt   time.Time
}

type ReminderLog struct {
	LessonID int64
	UserID   int64
	Kind     string
	SentAt   time.Time
}

type Subject struct {
	ID   int32
	Name string
}

type TrialFeedback struct {
	ID          int64
	LessonID    int64
	StudentID   int64
	TutorID     int64
	Liked       bool
	Comment     string
	ForwardedAt sql.NullTime
	CreatedAt   time.Time
}

type Tutor struct {
	UserID        int64
	Bio           string
	LessonMinutes int32
	PriceOverride sql.NullInt64
	Active        bool
}

type TutorException struct {
	ID       int64
	TutorID  int64
	FromDate time.Time
	ToDate   time.Time
	Note     string
}

type TutorProfile struct {
	ID            int64
	Name          string
	Role          string
	DebugRole     sql.NullString
	Grade         sql.NullInt16
	Tz            string
	ManagedBy     sql.NullInt64
	ConsentAt     sql.NullTime
	Bio           string
	LessonMinutes int32
	PriceOverride sql.NullInt64
	Active        bool
}

type TutorSubject struct {
	TutorID   int64
	SubjectID int32
}

type TutorWindow struct {
	ID       int64
	TutorID  int64
	Weekday  int16
	StartMin int32
	EndMin   int32
}

type User struct {
	ID        int64
	Name      string
	Role      string
	Grade     sql.NullInt16
	Tz        string
	ManagedBy sql.NullInt64
	ConsentAt sql.NullTime
	DebugRole sql.NullString
	CreatedAt time.Time
}

type UserSetting struct {
	UserID                int64
	RemindMorning         bool
	RemindHour            bool
	RescheduleNeedsParent bool
	Onboarded             bool
}

type UserState struct {
	UserID    int64
	State     string
	Data      json.RawMessage
	UpdatedAt time.Time
}
