// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
	"encoding/json"
)

const claimOutbox = `-- name: ClaimOutbox :many
UPDATE outbox SET next_attempt_at = now() + make_interval(secs => $1::float8), attempts = attempts + 1
WHERE id IN (
    SELECT o.id FROM outbox o
    WHERE o.provider = $2 AND o.status = 'pending' AND o.next_attempt_at <= now()
    ORDER BY o.id LIMIT $3
    FOR UPDATE SKIP LOCKED)
RETURNING id, provider, kind, chat_id, external_id, payload, attempts
`

type ClaimOutboxParams struct {
	LeaseSeconds float64
	Provider     string
	MaxRows      int32
}

type ClaimOutboxRow struct {
	ID         int64
	Provider   string
	Kind       string
	ChatID     string
	ExternalID string
	Payload    json.RawMessage
	Attempts   int32
}

// Берём пачку готовых записей провайдера и откладываем их на lease, чтобы параллельный
// диспетчер их не взял (FOR UPDATE SKIP LOCKED). После отправки — MarkOutboxSent или MarkOutboxRetry.
func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]ClaimOutboxRow, error) {
	rows, err := q.db.QueryContext(ctx, claimOutbox, arg.LeaseSeconds, arg.Provider, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimOutboxRow{}
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Kind,
			&i.ChatID,
			&i.ExternalID,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueOutbox = `-- name: EnqueueOutbox :exec
INSERT INTO outbox (provider, kind, chat_id, external_id, payload)
VALUES ($1, $2, $3, $4, $5)
`

type EnqueueOutboxParams struct {
	Provider   string
	Kind       string
	ChatID     string
	ExternalID string
	Payload    json.RawMessage
}

func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutbox,
		arg.Provider,
		arg.Kind,
		arg.ChatID,
		arg.ExternalID,
		arg.Payload,
	)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE outbox SET last_error = $1,
    next_attempt_at = now() + make_interval(secs => $2::float8),
    status = CASE WHEN attempts >= $3::int THEN 'failed' ELSE 'pending' END
WHERE id = $4
`

type MarkOutboxRetryParams struct {
	LastError    string
	DelaySeconds float64
	MaxAttempts  int32
	ID           int64
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxRetry,
		arg.LastError,
		arg.DelaySeconds,
		arg.MaxAttempts,
		arg.ID,
	)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox SET status = 'sent', sent_at = now(), last_error = '' WHERE id = $1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOutboxSent, id)
	return err
}

const pendingOutbox = `-- name: PendingOutbox :one
SELECT count(*)::int FROM outbox WHERE status = 'pending'
`

func (q *Queries) PendingOutbox(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, pendingOutbox)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const purgeOutbox = `-- name: PurgeOutbox :exec
DELETE FROM outbox WHERE status = 'sent' AND sent_at < now() - make_interval(secs => $1::float8)
`

func (q *Queries) PurgeOutbox(ctx context.Context, ageSeconds float64) error {
	_, err := q.db.ExecContext(ctx, purgeOutbox, ageSeconds)
	return err
}
