// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tutors.sql

package db

import (
	"context"
	"database/sql"
)

const activeEnrollments = `-- name: ActiveEnrollments :many
SELECT e.id, e.student_id, e.tutor_id, u.name AS tutor_name, e.subject_id, sb.name AS subject
FROM enrollments e JOIN users u ON u.id = e.tutor_id JOIN subjects sb ON sb.id = e.subject_id
WHERE e.student_id = $1 AND e.active ORDER BY e.id
`

type ActiveEnrollmentsRow struct {
	ID        int64
	StudentID int64
	TutorID   int64
	TutorName string
	SubjectID int32
	Subject   string
}

func (q *Queries) ActiveEnrollments(ctx context.Context, studentID int64) ([]ActiveEnrollmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, activeEnrollments, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveEnrollmentsRow{}
	for rows.Next() {
		var i ActiveEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TutorID,
			&i.TutorName,
			&i.SubjectID,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allTutorProfiles = `-- name: AllTutorProfiles :many
SELECT id, name, role, debug_role, grade, tz, managed_by, consent_at, bio, lesson_minutes, price_override, active FROM tutor_profiles ORDER BY name
`

func (q *Queries) AllTutorProfiles(ctx context.Context) ([]TutorProfile, error) {
	rows, err := q.db.QueryContext(ctx, allTutorProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TutorProfile{}
	for rows.Next() {
		var i TutorProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.DebugRole,
			&i.Grade,
			&i.Tz,
			&i.ManagedBy,
			&i.ConsentAt,
			&i.Bio,
			&i.LessonMinutes,
			&i.PriceOverride,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelFutureRecurringOfTutor = `-- name: CancelFutureRecurringOfTutor :exec
UPDATE lessons SET status = 'cancelled', cancel_reason = 'смена репетитора'
WHERE status = 'scheduled' AND starts_at > now() AND recurring_slot_id IN (
    SELECT rs.id FROM recurring_slots rs
    WHERE rs.student_id = $1 AND rs.tutor_id = $2 AND rs.subject_id = $3 AND rs.active)
`

type CancelFutureRecurringOfTutorParams struct {
	StudentID int64
	TutorID   int64
	SubjectID int32
}

func (q *Queries) CancelFutureRecurringOfTutor(ctx context.Context, arg CancelFutureRecurringOfTutorParams) error {
	_, err := q.db.ExecContext(ctx, cancelFutureRecurringOfTutor, arg.StudentID, arg.TutorID, arg.SubjectID)
	return err
}

const deactivateRecurringOfTutor = `-- name: DeactivateRecurringOfTutor :exec
UPDATE recurring_slots SET active = false
WHERE student_id = $1 AND tutor_id = $2 AND subject_id = $3
`

type DeactivateRecurringOfTutorParams struct {
	StudentID int64
	TutorID   int64
	SubjectID int32
}

func (q *Queries) DeactivateRecurringOfTutor(ctx context.Context, arg DeactivateRecurringOfTutorParams) error {
	_, err := q.db.ExecContext(ctx, deactivateRecurringOfTutor, arg.StudentID, arg.TutorID, arg.SubjectID)
	return err
}

const deleteException = `-- name: DeleteException :exec
DELETE FROM tutor_exceptions WHERE tutor_id = $1 AND id = $2
`

type DeleteExceptionParams struct {
	TutorID int64
	ID      int64
}

func (q *Queries) DeleteException(ctx context.Context, arg DeleteExceptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteException, arg.TutorID, arg.ID)
	return err
}

const deleteTutorSubject = `-- name: DeleteTutorSubject :execrows
DELETE FROM tutor_subjects WHERE tutor_id = $1 AND subject_id = $2
`

type DeleteTutorSubjectParams struct {
	TutorID   int64
	SubjectID int32
}

func (q *Queries) DeleteTutorSubject(ctx context.Context, arg DeleteTutorSubjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTutorSubject, arg.TutorID, arg.SubjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWindows = `-- name: DeleteWindows :exec
DELETE FROM tutor_windows WHERE tutor_id = $1
`

func (q *Queries) DeleteWindows(ctx context.Context, tutorID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWindows, tutorID)
	return err
}

const endOtherEnrollment = `-- name: EndOtherEnrollment :one
UPDATE enrollments SET active = false, ended_at = now()
WHERE student_id = $1 AND subject_id = $2 AND active AND tutor_id <> $3
RETURNING tutor_id
`

type EndOtherEnrollmentParams struct {
	StudentID int64
	SubjectID int32
	TutorID   int64
}

func (q *Queries) EndOtherEnrollment(ctx context.Context, arg EndOtherEnrollmentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, endOtherEnrollment, arg.StudentID, arg.SubjectID, arg.TutorID)
	var tutor_id int64
	err := row.Scan(&tutor_id)
	return tutor_id, err
}

const ensureTutor = `-- name: EnsureTutor :exec
INSERT INTO tutors (user_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureTutor(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, ensureTutor, userID)
	return err
}

const insertEnrollment = `-- name: InsertEnrollment :exec
INSERT INTO enrollments (student_id, tutor_id, subject_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertEnrollmentParams struct {
	StudentID int64
	TutorID   int64
	SubjectID int32
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, insertEnrollment, arg.StudentID, arg.TutorID, arg.SubjectID)
	return err
}

const insertException = `-- name: InsertException :exec
INSERT INTO tutor_exceptions (tutor_id, from_date, to_date, note)
VALUES ($1, ($2::text)::date, ($3::text)::date, $4)
`

type InsertExceptionParams struct {
	TutorID int64
	FromDay string
	ToDay   string
	Note    string
}

func (q *Queries) InsertException(ctx context.Context, arg InsertExceptionParams) error {
	_, err := q.db.ExecContext(ctx, insertException,
		arg.TutorID,
		arg.FromDay,
		arg.ToDay,
		arg.Note,
	)
	return err
}

const insertSubject = `-- name: InsertSubject :exec
INSERT INTO subjects (name) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) InsertSubject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, insertSubject, name)
	return err
}

const insertTutorSubject = `-- name: InsertTutorSubject :exec
INSERT INTO tutor_subjects (tutor_id, subject_id) VALUES ($1, $2)
`

type InsertTutorSubjectParams struct {
	TutorID   int64
	SubjectID int32
}

func (q *Queries) InsertTutorSubject(ctx context.Context, arg InsertTutorSubjectParams) error {
	_, err := q.db.ExecContext(ctx, insertTutorSubject, arg.TutorID, arg.SubjectID)
	return err
}

const insertWindow = `-- name: InsertWindow :exec
INSERT INTO tutor_windows (tutor_id, weekday, start_min, end_min) VALUES ($1, $2, $3, $4)
`

type InsertWindowParams struct {
	TutorID  int64
	Weekday  int16
	StartMin int32
	EndMin   int32
}

func (q *Queries) InsertWindow(ctx context.Context, arg InsertWindowParams) error {
	_, err := q.db.ExecContext(ctx, insertWindow,
		arg.TutorID,
		arg.Weekday,
		arg.StartMin,
		arg.EndMin,
	)
	return err
}

const isEnrolled = `-- name: IsEnrolled :one
SELECT EXISTS (SELECT 1 FROM enrollments
    WHERE student_id = $1 AND tutor_id = $2 AND subject_id = $3 AND active)
`

type IsEnrolledParams struct {
	StudentID int64
	TutorID   int64
	SubjectID int32
}

func (q *Queries) IsEnrolled(ctx context.Context, arg IsEnrolledParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isEnrolled, arg.StudentID, arg.TutorID, arg.SubjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listExceptions = `-- name: ListExceptions :many

SELECT id, to_char(from_date, 'YYYY-MM-DD')::text AS from_day, to_char(to_date, 'YYYY-MM-DD')::text AS to_day, note
FROM tutor_exceptions WHERE tutor_id = $1 AND to_date >= current_date - 1 ORDER BY from_date
`

type ListExceptionsRow struct {
	ID      int64
	FromDay string
	ToDay   string
	Note    string
}

// Даты исключений передаются текстом ГГГГ-ММ-ДД: так они не зависят от часового пояса сессии БД.
func (q *Queries) ListExceptions(ctx context.Context, tutorID int64) ([]ListExceptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExceptions, tutorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExceptionsRow{}
	for rows.Next() {
		var i ListExceptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromDay,
			&i.ToDay,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name FROM subjects ORDER BY id
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWindows = `-- name: ListWindows :many
SELECT weekday, start_min, end_min FROM tutor_windows WHERE tutor_id = $1 ORDER BY weekday, start_min
`

type ListWindowsRow struct {
	Weekday  int16
	StartMin int32
	EndMin   int32
}

func (q *Queries) ListWindows(ctx context.Context, tutorID int64) ([]ListWindowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWindows, tutorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWindowsRow{}
	for rows.Next() {
		var i ListWindowsRow
		if err := rows.Scan(&i.Weekday, &i.StartMin, &i.EndMin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTutorBio = `-- name: SetTutorBio :exec
UPDATE tutors SET bio = $1 WHERE user_id = $2
`

type SetTutorBioParams struct {
	Bio    string
	UserID int64
}

func (q *Queries) SetTutorBio(ctx context.Context, arg SetTutorBioParams) error {
	_, err := q.db.ExecContext(ctx, setTutorBio, arg.Bio, arg.UserID)
	return err
}

const setTutorDuration = `-- name: SetTutorDuration :exec
UPDATE tutors SET lesson_minutes = $1 WHERE user_id = $2
`

type SetTutorDurationParams struct {
	LessonMinutes int32
	UserID        int64
}

func (q *Queries) SetTutorDuration(ctx context.Context, arg SetTutorDurationParams) error {
	_, err := q.db.ExecContext(ctx, setTutorDuration, arg.LessonMinutes, arg.UserID)
	return err
}

const setTutorPrice = `-- name: SetTutorPrice :exec
UPDATE tutors SET price_override = $1 WHERE user_id = $2
`

type SetTutorPriceParams struct {
	PriceOverride sql.NullInt64
	UserID        int64
}

func (q *Queries) SetTutorPrice(ctx context.Context, arg SetTutorPriceParams) error {
	_, err := q.db.ExecContext(ctx, setTutorPrice, arg.PriceOverride, arg.UserID)
	return err
}

const tutorProfile = `-- name: TutorProfile :one
SELECT id, name, role, debug_role, grade, tz, managed_by, consent_at, bio, lesson_minutes, price_override, active FROM tutor_profiles WHERE id = $1
`

func (q *Queries) TutorProfile(ctx context.Context, id int64) (TutorProfile, error) {
	row := q.db.QueryRowContext(ctx, tutorProfile, id)
	var i TutorProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.DebugRole,
		&i.Grade,
		&i.Tz,
		&i.ManagedBy,
		&i.ConsentAt,
		&i.Bio,
		&i.LessonMinutes,
		&i.PriceOverride,
		&i.Active,
	)
	return i, err
}

const tutorProfilesBySubject = `-- name: TutorProfilesBySubject :many
SELECT tp.id, tp.name, tp.role, tp.debug_role, tp.grade, tp.tz, tp.managed_by, tp.consent_at, tp.bio, tp.lesson_minutes, tp.price_override, tp.active FROM tutor_profiles tp
JOIN tutor_subjects ts ON ts.tutor_id = tp.id
WHERE ts.subject_id = $1 AND tp.active
ORDER BY tp.name
`

func (q *Queries) TutorProfilesBySubject(ctx context.Context, subjectID int32) ([]TutorProfile, error) {
	rows, err := q.db.QueryContext(ctx, tutorProfilesBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TutorProfile{}
	for rows.Next() {
		var i TutorProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.DebugRole,
			&i.Grade,
			&i.Tz,
			&i.ManagedBy,
			&i.ConsentAt,
			&i.Bio,
			&i.LessonMinutes,
			&i.PriceOverride,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tutorStudents = `-- name: TutorStudents :many
SELECT DISTINCT u.id, u.name, u.role, u.grade, u.tz, u.managed_by, u.consent_at, u.debug_role, u.created_at FROM users u JOIN enrollments e ON e.student_id = u.id
WHERE e.tutor_id = $1 AND e.active ORDER BY u.id
`

func (q *Queries) TutorStudents(ctx context.Context, tutorID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, tutorStudents, tutorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Grade,
			&i.Tz,
			&i.ManagedBy,
			&i.ConsentAt,
			&i.DebugRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tutorSubjects = `-- name: TutorSubjects :many
SELECT s.id, s.name FROM subjects s JOIN tutor_subjects ts ON ts.subject_id = s.id
WHERE ts.tutor_id = $1 ORDER BY s.id
`

func (q *Queries) TutorSubjects(ctx context.Context, tutorID int64) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, tutorSubjects, tutorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
