// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const admins = `-- name: Admins :many
SELECT id, name, role, grade, tz, managed_by, consent_at, debug_role, created_at FROM users WHERE role = 'admin' ORDER BY id
`

func (q *Queries) Admins(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, admins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Grade,
			&i.Tz,
			&i.ManagedBy,
			&i.ConsentAt,
			&i.DebugRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const childrenOf = `-- name: ChildrenOf :many
SELECT u.id, u.name, u.role, u.grade, u.tz, u.managed_by, u.consent_at, u.debug_role, u.created_at FROM users u JOIN parent_links p ON p.student_id = u.id
WHERE p.parent_id = $1 ORDER BY u.id
`

func (q *Queries) ChildrenOf(ctx context.Context, parentID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, childrenOf, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Grade,
			&i.Tz,
			&i.ManagedBy,
			&i.ConsentAt,
			&i.DebugRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteState = `-- name: DeleteState :exec
DELETE FROM user_states WHERE user_id = $1
`

func (q *Queries) DeleteState(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteState, userID)
	return err
}

const getSettings = `-- name: GetSettings :one
SELECT remind_morning, remind_hour, reschedule_needs_parent, onboarded FROM user_settings WHERE user_id = $1
`

type GetSettingsRow struct {
	RemindMorning         bool
	RemindHour            bool
	RescheduleNeedsParent bool
	Onboarded             bool
}

func (q *Queries) GetSettings(ctx context.Context, userID int64) (GetSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSettings, userID)
	var i GetSettingsRow
	err := row.Scan(
		&i.RemindMorning,
		&i.RemindHour,
		&i.RescheduleNeedsParent,
		&i.Onboarded,
	)
	return i, err
}

const getState = `-- name: GetState :one
SELECT state, data FROM user_states WHERE user_id = $1
`

type GetStateRow struct {
	State string
	Data  json.RawMessage
}

func (q *Queries) GetState(ctx context.Context, userID int64) (GetStateRow, error) {
	row := q.db.QueryRowContext(ctx, getState, userID)
	var i GetStateRow
	err := row.Scan(&i.State, &i.Data)
	return i, err
}

const identities = `-- name: Identities :many
SELECT provider, external_id, chat_id, username FROM identities WHERE user_id = $1
`

type IdentitiesRow struct {
	Provider   string
	ExternalID string
	ChatID     string
	Username   string
}

func (q *Queries) Identities(ctx context.Context, userID int64) ([]IdentitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, identities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentitiesRow{}
	for rows.Next() {
		var i IdentitiesRow
		if err := rows.Scan(
			&i.Provider,
			&i.ExternalID,
			&i.ChatID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO identities (provider, external_id, user_id, chat_id, username)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdentityParams struct {
	Provider   string
	ExternalID string
	UserID     int64
	ChatID     string
	Username   string
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.Provider,
		arg.ExternalID,
		arg.UserID,
		arg.ChatID,
		arg.Username,
	)
	return err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invites (code, kind, created_by, target_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInviteParams struct {
	Code      string
	Kind      string
	CreatedBy int64
	TargetID  sql.NullInt64
	ExpiresAt time.Time
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.Code,
		arg.Kind,
		arg.CreatedBy,
		arg.TargetID,
		arg.ExpiresAt,
	)
	return err
}

const insertManagedChild = `-- name: InsertManagedChild :one
INSERT INTO users (name, role, grade, managed_by, consent_at)
VALUES ($1, 'student', $2, $3, now()) RETURNING id
`

type InsertManagedChildParams struct {
	Name      string
	Grade     sql.NullInt16
	ManagedBy sql.NullInt64
}

func (q *Queries) InsertManagedChild(ctx context.Context, arg InsertManagedChildParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertManagedChild, arg.Name, arg.Grade, arg.ManagedBy)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSettings = `-- name: InsertSettings :exec
INSERT INTO user_settings (user_id, onboarded) VALUES ($1, $2)
`

type InsertSettingsParams struct {
	UserID    int64
	Onboarded bool
}

func (q *Queries) InsertSettings(ctx context.Context, arg InsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, insertSettings, arg.UserID, arg.Onboarded)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (name, role) VALUES ($1, $2) RETURNING id
`

type InsertUserParams struct {
	Name string
	Role string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.Name, arg.Role)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isParentOf = `-- name: IsParentOf :one
SELECT EXISTS (SELECT 1 FROM parent_links WHERE parent_id = $1 AND student_id = $2)
`

type IsParentOfParams struct {
	ParentID  int64
	StudentID int64
}

func (q *Queries) IsParentOf(ctx context.Context, arg IsParentOfParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isParentOf, arg.ParentID, arg.StudentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkParent = `-- name: LinkParent :exec
INSERT INTO parent_links (parent_id, student_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkParentParams struct {
	ParentID  int64
	StudentID int64
}

func (q *Queries) LinkParent(ctx context.Context, arg LinkParentParams) error {
	_, err := q.db.ExecContext(ctx, linkParent, arg.ParentID, arg.StudentID)
	return err
}

const parentsOf = `-- name: ParentsOf :many
SELECT u.id, u.name, u.role, u.grade, u.tz, u.managed_by, u.consent_at, u.debug_role, u.created_at FROM users u JOIN parent_links p ON p.parent_id = u.id
WHERE p.student_id = $1 ORDER BY u.id
`

func (q *Queries) ParentsOf(ctx context.Context, studentID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, parentsOf, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Grade,
			&i.Tz,
			&i.ManagedBy,
			&i.ConsentAt,
			&i.DebugRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const preferredIdentity = `-- name: PreferredIdentity :one
SELECT provider, external_id, chat_id, username FROM identities
WHERE user_id = $1 ORDER BY last_seen_at DESC LIMIT 1
`

type PreferredIdentityRow struct {
	Provider   string
	ExternalID string
	ChatID     string
	Username   string
}

func (q *Queries) PreferredIdentity(ctx context.Context, userID int64) (PreferredIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, preferredIdentity, userID)
	var i PreferredIdentityRow
	err := row.Scan(
		&i.Provider,
		&i.ExternalID,
		&i.ChatID,
		&i.Username,
	)
	return i, err
}

const setConsent = `-- name: SetConsent :exec
UPDATE users SET consent_at = now() WHERE id = $1 AND consent_at IS NULL
`

func (q *Queries) SetConsent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setConsent, id)
	return err
}

const setDebugRole = `-- name: SetDebugRole :exec
UPDATE users SET debug_role = $1 WHERE id = $2
`

type SetDebugRoleParams struct {
	DebugRole sql.NullString
	ID        int64
}

func (q *Queries) SetDebugRole(ctx context.Context, arg SetDebugRoleParams) error {
	_, err := q.db.ExecContext(ctx, setDebugRole, arg.DebugRole, arg.ID)
	return err
}

const setGrade = `-- name: SetGrade :exec
UPDATE users SET grade = $1 WHERE id = $2
`

type SetGradeParams struct {
	Grade sql.NullInt16
	ID    int64
}

func (q *Queries) SetGrade(ctx context.Context, arg SetGradeParams) error {
	_, err := q.db.ExecContext(ctx, setGrade, arg.Grade, arg.ID)
	return err
}

const setName = `-- name: SetName :exec
UPDATE users SET name = $1 WHERE id = $2
`

type SetNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) SetName(ctx context.Context, arg SetNameParams) error {
	_, err := q.db.ExecContext(ctx, setName, arg.Name, arg.ID)
	return err
}

const setRole = `-- name: SetRole :exec
UPDATE users SET role = $1 WHERE id = $2
`

type SetRoleParams struct {
	Role string
	ID   int64
}

func (q *Queries) SetRole(ctx context.Context, arg SetRoleParams) error {
	_, err := q.db.ExecContext(ctx, setRole, arg.Role, arg.ID)
	return err
}

const touchIdentity = `-- name: TouchIdentity :exec
UPDATE identities SET chat_id = $1, username = $2, last_seen_at = now()
WHERE provider = $3 AND external_id = $4
`

type TouchIdentityParams struct {
	ChatID     string
	Username   string
	Provider   string
	ExternalID string
}

func (q *Queries) TouchIdentity(ctx context.Context, arg TouchIdentityParams) error {
	_, err := q.db.ExecContext(ctx, touchIdentity,
		arg.ChatID,
		arg.Username,
		arg.Provider,
		arg.ExternalID,
	)
	return err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO user_settings (user_id, remind_morning, remind_hour, reschedule_needs_parent, onboarded)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET remind_morning = EXCLUDED.remind_morning, remind_hour = EXCLUDED.remind_hour,
    reschedule_needs_parent = EXCLUDED.reschedule_needs_parent, onboarded = EXCLUDED.onboarded
`

type UpsertSettingsParams struct {
	UserID                int64
	RemindMorning         bool
	RemindHour            bool
	RescheduleNeedsParent bool
	Onboarded             bool
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings,
		arg.UserID,
		arg.RemindMorning,
		arg.RemindHour,
		arg.RescheduleNeedsParent,
		arg.Onboarded,
	)
	return err
}

const upsertState = `-- name: UpsertState :exec
INSERT INTO user_states (user_id, state, data, updated_at) VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE SET state = EXCLUDED.state, data = EXCLUDED.data, updated_at = now()
`

type UpsertStateParams struct {
	UserID int64
	State  string
	Data   json.RawMessage
}

func (q *Queries) UpsertState(ctx context.Context, arg UpsertStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertState, arg.UserID, arg.State, arg.Data)
	return err
}

const useInvite = `-- name: UseInvite :one
UPDATE invites SET used_at = now()
WHERE code = $1 AND used_at IS NULL AND expires_at > now()
RETURNING code, kind, created_by, target_id
`

type UseInviteRow struct {
	Code      string
	Kind      string
	CreatedBy int64
	TargetID  sql.NullInt64
}

func (q *Queries) UseInvite(ctx context.Context, code string) (UseInviteRow, error) {
	row := q.db.QueryRowContext(ctx, useInvite, code)
	var i UseInviteRow
	err := row.Scan(
		&i.Code,
		&i.Kind,
		&i.CreatedBy,
		&i.TargetID,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, name, role, grade, tz, managed_by, consent_at, debug_role, created_at FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Grade,
		&i.Tz,
		&i.ManagedBy,
		&i.ConsentAt,
		&i.DebugRole,
		&i.CreatedAt,
	)
	return i, err
}

const userByIdentity = `-- name: UserByIdentity :one
SELECT u.id, u.name, u.role, u.grade, u.tz, u.managed_by, u.consent_at, u.debug_role, u.created_at FROM users u
JOIN identities i ON i.user_id = u.id
WHERE i.provider = $1 AND i.external_id = $2
`

type UserByIdentityParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) UserByIdentity(ctx context.Context, arg UserByIdentityParams) (User, error) {
	row := q.db.QueryRowContext(ctx, userByIdentity, arg.Provider, arg.ExternalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Grade,
		&i.Tz,
		&i.ManagedBy,
		&i.ConsentAt,
		&i.DebugRole,
		&i.CreatedAt,
	)
	return i, err
}
